server:
  port: 8083

spring:
  application:
    name: notification-service
  profiles:
    active:
      - local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${project.variables.datasource.url}/trade_project
    username: ${project.variables.datasource.username}
    password: ${project.variables.datasource.password}
  flyway:
    enabled: true
    url: jdbc:postgresql://${project.variables.datasource.url}/trade_project
    user: ${project.variables.datasource.username}
    password: ${project.variables.datasource.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    trade-notification-topic: trade-notification-topic
    subscribe-status-topic: subscribe-status-topic
    consumer:
      bootstrap-servers: ${project.variables.kafka.url}
      group-id: notification-group
      auto-offset-reset: earliest
  mail:
    host: ${project.variables.mail.smtp.host}
    port: ${project.variables.mail.port}
    username: ${project.variables.mail.service.user}
    password: ${project.variables.mail.service.password}
    protocol: ${project.variables.mail.protocol}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

telegram:
  username: ${project.variables.telegram.username}
  botToken: ${project.variables.telegram.botToken}


project:
  variables:
    service-url: <?>
    datasource:
      url: <?>
      username: <?>
      password: <?>
    kafka:
      url: <?>
    telegram:
      username: <?>
      botToken: <?>
    mail:
      protocol: <?>
      service:
        user: <?>
        password: <?>
      smtp:
        host: <?>
      port: <?>

