spring:
  application:
    name: smart-service
  profiles:
    active:
      - local
  r2dbc:
    url: r2dbc:postgresql://${project.variables.datasource.url}/trade_project
    username: ${project.variables.datasource.username}
    password: ${project.variables.datasource.password}
  flyway:
    enabled: true
    url: jdbc:postgresql://${project.variables.datasource.url}/trade_project
    user: ${project.variables.datasource.username}
    password: ${project.variables.datasource.password}

grpc:
  server:
    port: 9090
    security:
      enabled: true
#      certificate-chain:
#      private-key:
    netty:
      use-native-transport: true


project:
  variables:
    datasource:
      url: <?>
      username: <?>
      password: <?>
  resources:
    finam:
      url: trade-api.finam.ru

