server:
  port: 8081

spring:
  application:
    name: ui-service
  profiles:
    active:
      - local
  thymeleaf:
    cache: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${project.variables.keycloak.client-id}
            client-secret: ${project.variables.keycloak.client-secret}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: ${project.variables.keycloak.url}/login/oauth2/code/keycloak
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: ${project.variables.keycloak.url}/realms/${project.variables.keycloak.realm}
            user-name-attribute: preferred_username
  redis:
    host: ${project.variables.redis.host}
    port: ${project.variables.redis.port}
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
    remote:
      secret: changeme

springdoc:
  info:
    title: Anastasia Trader Project
    description: API for UI-service
    version: 1.0.0
    url:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  paths-to-match: /api/v1/**


project:
  variables:
    service-url: <?>
    keycloak:
      url: <?>
      username: <?>
      password: <?>
      client-id: <?>
      client-secret: <?>
      realm: trade-project
    redis:
      host: <?>
      port: <?>
    core-service:
      url: <?>

  encryption:
    secret-key: <?>
    iv-value: <?>
