server:
  port: 8081

spring:
  application:
    name: ui-service
  profiles:
    active:
      - local
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${project.variables.keycloak.client-id}
            client-secret: ${project.variables.keycloak.client-secret}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://${project.variables.keycloak.url}/auth/realms/trade_project
  redis:
    host: ${project.variables.redis.host}
    port: ${project.variables.redis.port}
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
    remote:
      secret: changeme


project:
  variables:
    keycloak:
      url: localhost:8080
      client-id: client_id
      client-secret: client_secret
    redis:
      host: localhost
      port: 6379
