spring:
  application:
    name: telegram-bot
  profiles:
    active:
      - local
  kafka:
    consumer:
      bootstrap-servers: ${project.variables.kafka.url}
      group-id: telegram-bot-group
      auto-offset-reset: earliest
  redis:
    host: ${project.variables.redis.host}
    port: ${project.variables.redis.port}

telegrambots:
  bot:
    username: ${project.telegram.botToken}
    token: ${project.telegram.username}


project:
  variables:
    kafka:
      url: localhost:9092
    redis:
      host: localhost
      port: 6379
