spring:
  application:
    name: telegram-bot
  profiles:
    active:
      - local
  kafka:
    consumer:
      bootstrap-servers: ${project.variables.kafka.url}
      group-id: telegram-bot-group
      auto-offset-reset: earliest
  redis:
    host: ${project.variables.redis.host}
    port: ${project.variables.redis.port}

telegram:
  username: ${project.telegram.username}
  botToken: ${project.telegram.botToken}


project:
  variables:
    service-url: localhost:8080
    kafka:
      url: localhost:9092
    redis:
      host: localhost
      port: 6379
    core-service:
      url: http://localhost:8082
