spring:
  application:
    name: telegram-bot
  profiles:
    active:
      - local
  kafka:
    topic: transactions-topic
    consumer:
      bootstrap-servers: ${project.variables.kafka.url}
      group-id: telegram-bot-group
      auto-offset-reset: earliest
  redis:
    host: ${project.variables.redis.host}
    port: ${project.variables.redis.port}

telegram:
  username: ${project.telegram.username}
  botToken: ${project.telegram.botToken}


project:
  variables:
    service-url: <?>
    kafka:
      url: <?>
    redis:
      host: <?>
      port: <?>
    core-service:
      url: <?>
